### ISSUE TITLE
spampd tries to use Unix socket when not defined

### ISSUE THREAD

**Issue by valeriangalliat** [mpaperno/spampd#15] opened 2017-09-29 17:03 UTC
I'm running spampd with Perl 5.22.3, and [this line](https://github.com/mpaperno/spampd/blob/8cdc4c66fd873a9830ba63379a73696279bb0d1f/spampd.pl#L992) is returning true even though `$socket` is actually not set anywhere.

I'm not sure if it's related to the version of Perl I'm using, but basically if I do:

```perl
my $x = defined $socket; 
print "'${x}' '${socket}'\n";
```

I get `'1' ''`.

This causes the `|unix` string to be added to `@ports`, resulting in the following error: `
Could not determine port number from host [*]:unix`.

Any idea why this happens and how to fix it? I'd like to help but I really don't know much about Perl.

**Comment by mpaperno** [comment] 2018-05-01 15:44
Caused by 8cdc4c6, fixed in ee66b26 (#18)

**Closed by mpaperno** 2018-05-01 15:44 UTC
